### PR TITLE
Remove duplicate dependencies, Add Node-Sass dep., fix broken build

### PR DESCRIPTION
**Pull request by alloro**
I tried the [FirstAidGit Installation](https://github.com/magalhini/firstaidgit#how-to-run) steps without success, due to missing dependencies. I added the dep. and removed duplicates and voila everything worked.

### Env:
**Node**: 8.1.3
**Npm**: 5.0.4
**Gulp**: 3.9.1

### CODE REVIEW

**Comment by RichardLitt** [comment]
Hey @alloro  - any reason this was deleted?

**Comment by alloro** [comment]
@RichardLitt stale PR for a long time. If @magalhini decides to use it I can open it again.

**Comment by RichardLitt** [comment]
I'll go ahead and look at it; I know that @magalhini is pressed for time. Sorry about the delay!

**Comment by alloro** [comment]
@RichardLitt ok, thanks!

**Comment by RichardLitt** [comment]
Spent some time on this. Rebased, updated gulp-sass,and this works well. Thanks, @alloro. Sorry about the delay! 

Merged in c0e8b36ed799005f5ffdfd41d144286ca4fb8656.

**Pull request closed without merging**
