### PR TITLE
Added command to show file content at a specific commit

### PR DESCRIPTION
**Pull request by atishgoswami**

### CODE REVIEW

**Comment by magalhini** [comment]
Thanks @atishgoswami !

**Comment by atishgoswami** [comment]
@magalhini first of all thanks for accepting by pull request.

I was just wondering if these changes have be deployed to http://firstaidgit.io/.

Regards,

**Comment by magalhini** [comment]
@atishgoswami Not yet! I'm having trouble running my own build, mainly due to node 4.x failing with node-sass... I simply can't get this to work. I need a running build before deploying, so all the recent PR are on hold :( might need to actually downgrade node to get this to work.

**Comment by atishgoswami** [comment]
@magalhini Ya I was having the same problem too, build was failing due to the same node-sass issue,
had to down grade the node version from 4.x to 0.10.26, and finally I had a working build :D

**Comment by magalhini** [comment]
The build was finally fixed! Kudos to @Couto for figuring out how to solve the node-sass dependencies issues :)

**Pull request merged**
